import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Lead Frontend Engineer',
    company: 'AAAAAAAA',
    logo: '/images/careers/sirka.png',
    location: 'BBBBBBBB',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2022-03',
    end_date: null,
    industry: 'wellness',
    link: 'https://sirka.io',
  },
  {
    position: 'Sr. Frontend Engineer',
    company: 'AAAAAAAA',
    logo: '/images/careers/sirka.png',
    location: 'AAAAAAAA',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2021-12',
    end_date: '2022-03',
    industry: 'wellness',
    link: 'AAAAAAAA',
  },
  {
    position: 'Frontend Developer',
    company: 'AAAAAAAA',
    logo: '/images/careers/paper-id.png',
    location: 'AAAAAAAA',
    location_type: 'Hybrid',
    type: 'Fulltime',
    start_date: '2020-02',
    end_date: '2021-12',
    industry: 'financing',
    link: 'AAAAAAAA',
  },
  {
    position: 'Full-Stack Developer',
    company: 'Gama Plantation',
    logo: '/images/careers/kpn.png',
    location: 'AAAAAAAA',
    location_type: 'Onsite',
    type: 'Fulltime',
    start_date: '2019-09',
    end_date: '2020-02',
    industry: 'agriculture',
    link: 'AAAAAAAA',
  },
  {
    position: 'Full-Stack Developer',
    company: 'Rencong Network',
    logo: '/images/careers/rencong.png',
    location: 'AAAAAAAA',
    location_type: 'Onsite',
    type: 'Freelance',
    start_date: '2014-12',
    end_date: '2019-09',
    industry: 'software house',
    link: 'AAAAAAAA',
  },
  {
    position: 'Web Developer',
    company: 'AAAAAAAA',
    logo: null,
    location: 'AAAAAAAA',
    location_type: 'Onsite',
    type: 'Part-time',
    start_date: '2016-12',
    end_date: '2017-08',
    industry: 'travel',
    link: 'AAAAAAAA',
  },
  {
    position: 'Web Developer',
    company: 'RAAAAAAAA',
    logo: '/images/careers/riab.png',
    location: 'AAAAAAAA',
    location_type: 'Onsite',
    type: 'Part-time',
    start_date: '2015-01',
    end_date: '2016-01',
    industry: 'school',
    link: 'AAAAAAAA',
  },
];
